-- Generated by Babelfish script, do not add strings manually, only translate existing strings.
-- This is the base locale; values can be "true" so they default to their key, or any string to override that behaviour.
local L = LibStub("AceLocale-3.0"):NewLocale("MagicLooter", "enUS", true)


L["A newline separated list of bankers. All loot that isn't disenchantable will be given to the people on the list in the order they appear. If none of the names are valid loot targets, the loot will be given to the player."] = true
L["A newline separated list of disenchanters. All disenchantable loot will be given to the people on the list in the order they appear. If none of the names are valid loot targets, the loot will be given to the player."] = true
L["Announce Loot Recipients"] = true
L["Auto Loot Threshold"] = true
L["Auto-looting %s to %s for banking."] = true
L["Auto-looting %s to %s for disenchanting."] = true
L["Banker Priority List"] = true
L["Disenchant Threshold"] = true
L["Disenchanter Priority List"] = true
L["Enable Minimap Icon"] = true
L["Epic"] = true
L["Magic Looter"] = true
L["Only auto loot items below and including the selected rarity."] = true
L["Only consider items at or below this threshold as disenchantable. Items not considered disenchantable will be auto looted using the banker list instead of the disenchanter list."] = true
L["Options"] = true
L["Print a massage, only visible by you, when Magic Looter autoloots an item."] = true
L["Rare"] = true
L["Show an icon to open the Magic Looter config at the minimap."] = true
L["Uncommon"] = true
L["|cffffffffMagic Looter|r\n|cffffff00Left click|r to open the configuration pane.\n"] = true
